# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='role',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Apprentice', 'Apprentice'), ('TA', 'TA')], default='Lead', max_length=350),
        ),
    ]
