# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20161102_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='four_person',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='half_class',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='pairs',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='three_person',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
